---
  - name: Include OS-specific variables.
    include_vars: "{{ ansible_os_family }}.yml"

  - name: NETDATA | Check if present
    stat:
      path: "{{ netdata_install_dir }}/netdata"
    register: netdata_present
  - debug: msg="netdata not installed"
    when: netdata_present.stat.exists == False
  - debug: msg="netdata installed"
    when: netdata_present.stat.exists == True

  - name: NETDATA | Install package dependencies
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ netdata_deps }}"
    when: netdata_present.stat.exists == False
    become: yes
    tags:
     - netdata

  - name: NETDATA | Clone or Pull for Install or Update
    git:
      repo: https://github.com/firehol/netdata.git
      dest: "{{ netdata_install_dir}}/netdata"
      depth: 1
      dest: /tmp/netdata
    register: clone_or_pull
    tags:
      - netdata
  - debug: var=clone_or_pull

  - name: NETDATA | Build and install
    shell: "./netdata-installer.sh --install {{ netdata_install_dir }} --dont-wait"
    args:
      chdir: /tmp/netdata
    when: clone_or_pull.changed == True
    become: yes
    tags:
      - netdata
    notify: stop service

- meta: flush_handlers

  - name: stop service
    service:
      name: netdata
      state: stopped
    notify: copy service file

  - name: copy service file
    command: cp /tmp/netdata/system/netdata.service /etc/systemd/system/
    when: ansible_service_mgr == systemd
    notify: start and enable service

  - name: copy service file
    command: cp /tmp/netdata/system/netdata-lsb /etc/init.d/netdata
    when: ansible_service_mgr == init
    notify: start and enable service

  - name: start and enable service
    service:
      name: netdata
      state: started
      enabled: yes
    when: clone_or_pull.changed == True
    become: true
    tags:
      - netdata
