---
# handlers file for leanbit.netdata
- name: stop service
  service:
    name: netdata
    state: stopped

- name: start and enable service
  service:
    name: netdata
    state: started
    enabled: yes
    daemon_reload: yes
  when: clone_or_pull.changed == True
  become: true
  tags:
    - netdata
